#!/bin/bash

#
# Copyright (C) 2015 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see .
#

# including file to get access of PROXY variables
. /etc/sysconfig/phone-home

# get status variable from config file
STATUS=`/sbin/e-smith/config getprop phone-home status`

# check if status if disabled
if [ "$STATUS" == "disabled" ]; then
   exit 0
fi

if [ "x$PROXY_SERVER" != "x" ]; then
   # set param curl
   PROXY_OPTIONS_SERVER="--proxy http://$PROXY_SERVER"
else
   # default
   PROXY_OPTIONS_SERVER=""
fi

if [ "x$PROXY_PORT" != "x" ]; then
   # set param curl
   PROXY_OPTIONS_SERVER="$PROXY_OPTIONS_SERVER:$PROXY_PORT"
else
   # default
   PROXY_OPTIONS_SERVER=""
fi

if [ "x$PROXY_USER" != "x" ]; then
   # set param curl
   PROXY_OPTIONS_USER="--proxy-user $PROXY_USER"
else
   # default
   PROXY_OPTIONS_USER=""
fi

if [ "x$PROXY_PASS" != "x" ]; then
   # set param curl
   PROXY_OPTIONS_USER="$PROXY_OPTIONS_USER:$PROXY_PASS"
else
   # default
   PROXY_OPTIONS_USER=""
fi

#get proxy options
PROXY_OPTIONS="$PROXY_OPTIONS_SERVER $PROXY_OPTIONS_USER"

#get uuid and release
UUID=`/sbin/e-smith/config getprop phone-home uuid`
RELEASE=`/sbin/e-smith/config getprop sysconfig Version`

#send data
curl -s -X POST --data "method=add_info&uuid=$UUID&release=$RELEASE" $PROXY_OPTIONS http://$SERVER_IP/phone-home/index.php

